[project]
name = "gitscanner"
version = "0.1.0"
description = "Scan project groups for open Git repositories."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []


[project.scripts]
gitscanner = "gitscanner.gitscanner:main"

